# Generated by Django 4.2.3 on 2023-11-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_usermodel_first_name_alter_usermodel_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_address',
            field=models.CharField(default='Address is not indicated', max_length=40, verbose_name='User address'),
        ),
    ]
