# Generated by Django 4.2.3 on 2023-11-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_profile', '0002_alter_cinema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
