# Generated by Django 4.2.6 on 2023-10-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(default='', max_length=300, null=True)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='posters')),
                ('rating', models.PositiveIntegerField()),
                ('actors', models.ManyToManyField(related_name='movies', to='actors.actors')),
            ],
        ),
    ]
