# Generated by Django 4.2.6 on 2023-10-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_data', '0002_movie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='undecided', max_length=255, unique=True)),
                ('movie', models.ManyToManyField(related_name='collection', to='show_data.movie')),
            ],
        ),
    ]
