# Generated by Django 4.2.6 on 2023-10-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_data', '0003_alter_movie_date_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='city',
            field=models.CharField(default='undecided', max_length=30),
        ),
    ]
