# Generated by Django 4.2.6 on 2023-10-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_data', '0004_movie_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.AddField(
            model_name='movie',
            name='name_original',
            field=models.CharField(default='undecided', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='name_translated',
            field=models.CharField(default='undecided', max_length=100, unique=True),
        ),
    ]
