# Generated by Django 4.2.6 on 2023-10-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_data', '0006_genre_movie_duration_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='show_data.genre'),
        ),
    ]
