# Generated by Django 4.2.3 on 2023-11-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_data', '0007_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name_original',
            new_name='name',
        ),
    ]
