# Generated by Django 4.2.6 on 2023-10-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='undecided', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='undecided', max_length=20)),
                ('last_name', models.CharField(default='undecided', max_length=20)),
                ('sure_name', models.CharField(default='undecided', max_length=20)),
                ('jobs', models.ManyToManyField(related_name='actors', to='actors.jobs')),
                ('prizes', models.ManyToManyField(related_name='actors', to='actors.prizes')),
            ],
        ),
    ]
